"""empty message

Revision ID: 3c202a0a0e42
Revises: 
Create Date: 2020-06-16 19:08:22.305974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c202a0a0e42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open', sa.String(length=255), nullable=True),
    sa.Column('high', sa.String(length=255), nullable=True),
    sa.Column('low', sa.String(length=255), nullable=True),
    sa.Column('close', sa.String(length=255), nullable=True),
    sa.Column('volume', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('marketOpen', sa.String(length=255), nullable=True),
    sa.Column('marketClose', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('matchScore', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('idade', sa.String(length=255), nullable=True),
    sa.Column('profissao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('empresa')
    op.drop_table('cotacao')
    # ### end Alembic commands ###
